import type {
  AuditAction,
  AuditEntityType,
} from "@/features/audit/types/audit-log.types";

export const auditActionLabels: Record<AuditAction, string> = {
  USER_CREATED: "Usuario creado",
  USER_UPDATED: "Usuario actualizado",
  USER_DEACTIVATED: "Usuario desactivado",
  USER_REACTIVATED: "Usuario reactivado",
  CATEGORY_CREATED: "Categoria creada",
  CATEGORY_UPDATED: "Categoria actualizada",
  CATEGORY_DEACTIVATED: "Categoria desactivada",
  CATEGORY_REACTIVATED: "Categoria reactivada",
  SALES_CHANNEL_CREATED: "Canal creado",
  SALES_CHANNEL_UPDATED: "Canal actualizado",
  SALES_CHANNEL_DEACTIVATED: "Canal desactivado",
  SALES_CHANNEL_REACTIVATED: "Canal reactivado",
  PRODUCT_CREATED: "Producto creado",
  PRODUCT_UPDATED: "Producto actualizado",
  PRODUCT_DEACTIVATED: "Producto desactivado",
  PRODUCT_REACTIVATED: "Producto reactivado",
  PRODUCT_COST_CREATED: "Costo creado",
  PRODUCT_PRICE_CREATED: "Precio creado",
  INVENTORY_STOCK_IN: "Ingreso de stock",
  INVENTORY_MANUAL_ADJUSTMENT: "Ajuste manual",
  INVENTORY_WASTE: "Merma",
  INVENTORY_RETURN_IN: "Reingreso",
  INVENTORY_SALE_OUT: "Salida por venta",
  INVENTORY_VOID_REVERSAL: "Reversion por anulacion",
  INVENTORY_MINIMUM_STOCK_UPDATED: "Minimo actualizado",
  SALE_TICKET_CREATED: "Ticket creado",
  SALE_TICKET_UPDATED: "Ticket actualizado",
  SALE_TICKET_CANCELLED: "Ticket cancelado",
  SALE_TICKET_ITEM_ADDED: "Item agregado",
  SALE_TICKET_ITEM_UPDATED: "Item actualizado",
  SALE_TICKET_ITEM_REMOVED: "Item removido",
  SALE_TICKET_CONFIRMED: "Ticket confirmado",
  SALE_TICKET_VOIDED: "Ticket anulado",
};

export const auditEntityLabels: Record<AuditEntityType, string> = {
  USER: "Usuario",
  CATEGORY: "Categoria",
  SALES_CHANNEL: "Canal",
  PRODUCT: "Producto",
  PRODUCT_COST_HISTORY: "Costo historico",
  PRODUCT_PRICE_HISTORY: "Precio historico",
  PRODUCT_STOCK: "Stock de producto",
  INVENTORY_MOVEMENT: "Movimiento de inventario",
  SALE_TICKET: "Ticket de venta",
  SALE_TICKET_ITEM: "Item de ticket",
  SYSTEM: "Sistema",
};
